package baseBall.player;

public enum POSITION_INFO {
	PITCHER,
	FIRST_BASE_FIELDER,
	SECOND_BASE_FIELDER,
	THIRD_BASE_FIELDER,
	RIGHT_FIELDER,
	SHORTSTOP,
	LEFT_FIELDER,
	CENTER_FIELDER,
	DESIGNATED_HITTER,
	CATCHER
}